### ISSUE TITLE
autologin

### ISSUE THREAD

**Issue by batphil** [cakebaker/oauth-consumer#6]
Can you explain me how to autologin with account params defined manually in php code ?

**Comment by batphil** [comment]
I'm not very familiar with oauth/twitter API, and i try this : http://stackoverflow.com/questions/29539281/twitter-api-request-with-autologin

**Comment by cakebaker** [comment]
Hm, the code in the referenced question looks fine to me, and making that request to Twitter works fine here. Did you <code>debug</code> what is returned from the <code>get()</code> method? What status code is returned?

**Comment by cakebaker** [comment]
Closing this ticket as it works for me.
