### ISSUE TITLE
Set Authorization header

### ISSUE THREAD

**Issue by fvelcker** [cakebaker/oauth-consumer#8]
Hello,

Might be a stupid question, but I have to set a the Authorization like this

```
Authorization : Basic [Base64 KEY:SECRET]
```

Is there anyway to do this ?

Thanks

**Comment by cakebaker** [comment]
No, that's not possible :|  The <code>request</code> method allows you to set all kinds of headers, with the exception of the <code>Authorization</code> header, which is set to <code>OAuth</code>...

**Comment by fvelcker** [comment]
Ok, no worries.
I don't need too much actually so I am just going to use Cake HttpSocket, should be fine.

Thank you
